import type { CameraScoutItem, PublicCamera } from "../types/dashboard";

export const phuketPublicCameras: PublicCamera[] = [
  {
    id: "patong-coast-verified",
    label: "Patong Coast",
    location: "Patong coast",
    locationLabel: "Patong beachfront",
    lat: 7.8964,
    lng: 98.2961,
    provider: "SCS Webcam",
    type: "beach",
    validationState: "verified",
    focusArea: "Patong coast",
    strategicNote:
      "Use this as the governor's first look for surf, beach density, and visible weather posture on the island's most watched coast.",
    notes:
      "Verified west-coast camera with direct value for surf condition, crowd temperature, and the public optics of sea safety messaging.",
    accessUrl: "https://webcam.scs.com.ua/en/asia/thailand/phuket/coast/",
    corridorIds: ["airport-patong", "west-beaches"],
    lastValidatedAt: "2026-03-15T00:00:00.000Z",
  },
  {
    id: "karon-panorama-verified",
    label: "Karon Panorama",
    location: "Karon beachfront",
    locationLabel: "Karon beachfront",
    lat: 7.8308,
    lng: 98.294,
    provider: "SCS Webcam",
    type: "beach",
    validationState: "verified",
    focusArea: "Karon beachfront",
    strategicNote:
      "Confirms west-coast sea state south of Patong and helps separate localized surf noise from broader monsoon deterioration.",
    notes:
      "Verified panorama for Karon's shoreline, surf conditions, and broad beachfront activity.",
    accessUrl: "https://webcam.scs.com.ua/en/asia/thailand/phuket/karon/",
    corridorIds: ["west-beaches"],
    lastValidatedAt: "2026-03-15T00:00:00.000Z",
  },
  {
    id: "kata-beach-verified",
    label: "Kata Beach",
    location: "Kata coast",
    locationLabel: "Kata beachfront",
    lat: 7.8198,
    lng: 98.299,
    provider: "SSS Phuket",
    type: "beach",
    validationState: "verified",
    focusArea: "Kata coast",
    strategicNote:
      "Useful for surf risk, beach occupancy, and whether west-coast conditions are worsening south of Karon.",
    notes:
      "Verified live beach camera for Kata with good visibility into waves, rain bands, and public crowding.",
    accessUrl: "https://www.sssphuket.com/kata-beach-live-cam/",
    corridorIds: ["west-beaches"],
    lastValidatedAt: "2026-03-15T00:00:00.000Z",
  },
  {
    id: "bangla-road-verified",
    label: "Bangla Road",
    location: "Patong nightlife core",
    locationLabel: "Bangla Road",
    lat: 7.8934,
    lng: 98.2985,
    provider: "SCS Webcam",
    type: "traffic",
    validationState: "verified",
    focusArea: "Patong coast",
    strategicNote:
      "Shows city vibe, nightlife density, and whether public narrative about crowding or disorder is grounded in reality.",
    notes:
      "Verified street-facing camera for Patong's highest-visibility nightlife block.",
    accessUrl: "https://webcam.scs.com.ua/en/asia/thailand/phuket/banglaroud/",
    corridorIds: ["west-beaches"],
    lastValidatedAt: "2026-03-15T00:00:00.000Z",
  },
  {
    id: "old-town-verified",
    label: "Phuket Old Town",
    location: "Phuket town center",
    locationLabel: "Phuket Old Town",
    lat: 7.884,
    lng: 98.3923,
    provider: "SCS Webcam",
    type: "traffic",
    validationState: "verified",
    focusArea: "Phuket Old Town",
    strategicNote:
      "Lets the governor check downtown tempo, event spillover, and whether online claims about the city vibe match reality.",
    notes:
      "Verified old-town camera useful for civic mood, access, and downtown event posture.",
    accessUrl: "https://webcam.scs.com.ua/en/asia/thailand/phuket/oldtown/",
    corridorIds: ["old-town"],
    lastValidatedAt: "2026-03-15T00:00:00.000Z",
  },
  {
    id: "airport-access-scout",
    label: "Airport Access Scout",
    location: "Airport corridor",
    locationLabel: "Phuket Airport access",
    lat: 8.1132,
    lng: 98.3169,
    provider: "Scout target",
    type: "traffic",
    validationState: "candidate",
    focusArea: "Airport corridor",
    strategicNote:
      "Highest-priority scout slot for seeing queue build-up, transfer pace, and weather-linked road disruption at the airport end.",
    notes:
      "Candidate source pending validation. Keep the slot visible so the governor sees the surveillance gap in the arrival corridor.",
    accessUrl: null,
    corridorIds: ["airport-patong"],
    candidateSourceNote: "Candidate source pending validation",
  },
  {
    id: "chalong-pier-scout",
    label: "Chalong Pier Scout",
    location: "Chalong Pier",
    locationLabel: "Chalong Pier",
    lat: 7.8227,
    lng: 98.3409,
    provider: "Scout target",
    type: "bay",
    validationState: "candidate",
    focusArea: "Chalong / Rassada / Ao Po",
    strategicNote:
      "Needed to verify departure tempo, rain exposure, and queue pressure on the Chalong side.",
    notes:
      "Candidate source pending validation for the governor's east-coast pier watch.",
    accessUrl: null,
    corridorIds: ["east-coast-ports"],
    candidateSourceNote: "Candidate source pending validation",
  },
  {
    id: "rassada-pier-scout",
    label: "Rassada Pier Scout",
    location: "Rassada Pier",
    locationLabel: "Rassada Pier",
    lat: 7.8799,
    lng: 98.4215,
    provider: "Scout target",
    type: "bay",
    validationState: "candidate",
    focusArea: "Chalong / Rassada / Ao Po",
    strategicNote:
      "Needed for ferry queue discipline, passenger density, and whether pier messaging is landing.",
    notes:
      "Candidate source pending validation for the main ferry gateway into island operations.",
    accessUrl: null,
    corridorIds: ["east-coast-ports"],
    candidateSourceNote: "Candidate source pending validation",
  },
  {
    id: "ao-po-marina-scout",
    label: "Ao Po Marina Scout",
    location: "Ao Po Marina",
    locationLabel: "Ao Po Marina",
    lat: 8.0724,
    lng: 98.4624,
    provider: "Scout target",
    type: "bay",
    validationState: "candidate",
    focusArea: "Chalong / Rassada / Ao Po",
    strategicNote:
      "Needed to watch marina density, yacht staging, and east-coast sea access without sending a field team first.",
    notes:
      "Candidate source pending validation for the marina and bay-approach picture.",
    accessUrl: null,
    corridorIds: ["east-coast-ports"],
    candidateSourceNote: "Candidate source pending validation",
  },
  {
    id: "ao-nang-scout",
    label: "Ao Nang Beachfront Scout",
    location: "Ao Nang waterfront",
    locationLabel: "Ao Nang beachfront",
    lat: 8.0323,
    lng: 98.8237,
    provider: "Scout target",
    type: "beach",
    validationState: "candidate",
    focusArea: "Ao Nang",
    strategicNote:
      "Needed to read Krabi-side visitor density, longtail queueing, and open-water conditions that directly feed Phuket ferries and tours.",
    notes:
      "Candidate source pending validation for the Krabi-facing tourism corridor.",
    accessUrl: null,
    corridorIds: ["ao-nang-krabi"],
    candidateSourceNote: "Candidate source pending validation",
  },
  {
    id: "khao-lak-scout",
    label: "Khao Lak Coast Scout",
    location: "Khao Lak coast",
    locationLabel: "Khao Lak coast",
    lat: 8.6367,
    lng: 98.2487,
    provider: "Scout target",
    type: "beach",
    validationState: "candidate",
    focusArea: "Khao Lak",
    strategicNote:
      "Needed to confirm coast conditions, beach posture, and resort-side public narrative north of Phuket.",
    notes:
      "Candidate source pending validation for the Khao Lak and Phang Nga watchline.",
    accessUrl: null,
    corridorIds: ["khao-lak-phang-nga"],
    candidateSourceNote: "Candidate source pending validation",
  },
];

export const cameraScoutTargets: CameraScoutItem[] = phuketPublicCameras.filter(
  (camera): camera is CameraScoutItem => camera.validationState === "candidate",
);
